### ISSUE TITLE
The `cmd` handler should delete the user command in its `before` method

### ISSUE THREAD

**Issue by xulongwu4** [BirdeeHub/lze#15]
Currently the `cmd` handler's before method does not call `nvim_del_user_command(cmd)` to clear the command hook. This is an issue if the plugin does not override existing user commands with the same name as what the plugin intends to define.

For example, the [`vim-startup`](https://github.com/dstein64/vim-startuptime) plugin defines a `StartupTime` command only if the user does not already define such a command. Now if I have the following spec:

```lua
 {
    name = "vim-startuptime",
    cmd = "StartupTime",
    keys = { { "<leader>st", function() vim.cmd.StartupTime() end, desc = "Vim startup time" } },
 }
```

Lazy-loading on the keys `<leader>st` would fail with message "Command `StartupTime` not found after loading ``".

This is because `lze` creates a user command `StartupTime` to handle the `cmd` key. However, this customized user command is never cleared in the cmd handler's `before` method. When the plugin is loaded by the keys handler, it tries to run `vim.cmd.StartupTime()`. Because the plugin does not try to override the existing `StartupTime` command, we will be running the customized version of "StartupTime", instead of the one that should have been defined by the plugin.

**Comment by BirdeeHub** [comment]
Ok.

I think I might  have fixed the issue in a private branch, but still working on a proper test for it.

But Im on it :)

Thanks for reporting. Will close once I push and merge stuff.

**Comment by BirdeeHub** [comment]
So, it got late last night and I had to go to sleep, but Im having trouble reproducing this in an isolated way for a test, but can easily reproduce in my personal config, and deleting the command at the correct time seems to fix the bug, but also breaks a lot of tests.

I am going to have to do some investigating as to whether the tests are breaking because they are badly written or if my fix is not a fix.

So, it might be a few days but I am at least aware of the issue and working on it :)

**Comment by BirdeeHub** [comment]
actually, I now see why I was having trouble reproducing in a test

vim-startuptime does this

```vim
if !exists(':StartupTime')
  command -nargs=* -complete=custom,startuptime#CompleteOptions StartupTime
        \ :call startuptime#StartupTime(<q-mods>, <f-args>)
endif
```

It checks if the comand exists first before it makes it.

With this new info I should be able to make a proper tests and iterate with more quickly. Should have some time to work on this today hopefully.

**Comment by BirdeeHub** [comment]
WE HAVE A TEST

```lua
    it("Deletes command before loading the plugin when other specs load it", function()
        local should_be_inc = 0
        local plugin = {
            name = "my_other_plus_cmd",
            cmd = "MyTestCMD",
            load = function(name)
                if vim.fn.exists(":MyTestCMD") == 0 then
                    vim.api.nvim_create_user_command('MyTestCMD', function(opts)
                        should_be_inc = should_be_inc + 1
                    end, {})
                end
            end,
        }
        lze.load(plugin)
        lze.trigger_load(plugin.name)
        vim.cmd[plugin.cmd]()
        assert.equal(1, should_be_inc)
    end)
```

Now I can make sure I fix it properly :)

**Comment by BirdeeHub** [comment]
Fixed! will take some time before it lands on nixpkgs, I have an open PR to nixpkgs for 0.1.3 so ill update that to 0.1.4

EDIT: So, I DID have one open... and it was merged literally right before I updated it....

Hopefully he is still around and  can hit me with 1 more.

https://github.com/NixOS/nixpkgs/pull/351027

**Comment by BirdeeHub** [comment]
but you can use it right away from the flake or luarocks or downloading straight from github with any nvim package manager

**Comment by BirdeeHub** [comment]
I suppose Ill leave this issue open until it merges into nixpkgs so ppl on nix know about it.

**Comment by BirdeeHub** [comment]
https://nixpk.gs/pr-tracker.html?pr=351963 😊 When its all green checkmarks I can close the issue :)
